"""Centralized ACP lifecycle and schema contracts."""

# Status values
QUEUED = "QUEUED"
EVALUATING = "EVALUATING"
COMPLETED = "COMPLETED"
REFUSED = "REFUSED"
FAILED = "FAILED"
DEAD_LETTER = "DEAD_LETTER"

STATUSES = (
    QUEUED,
    EVALUATING,
    COMPLETED,
    REFUSED,
    FAILED,
    DEAD_LETTER,
)

# Failure reasons
PRECHECK_INVALID = "PRECHECK_INVALID"
TASK_FILE_MISSING = "TASK_FILE_MISSING"
TASK_FILE_INVALID = "TASK_FILE_INVALID"
REPO_PATH_INVALID = "REPO_PATH_INVALID"
RUNNER_EXCEPTION = "RUNNER_EXCEPTION"
GATE_REFUSED = "GATE_REFUSED"
VERIFICATION_FAILED = "VERIFICATION_FAILED"
UNKNOWN_FAILURE = "UNKNOWN_FAILURE"
LOCK_HELD = "LOCK_HELD"

# Dead letter reasons
INVARIANT_VIOLATION = "INVARIANT_VIOLATION"
RETRIES_EXHAUSTED = "RETRIES_EXHAUSTED"

# Event types
EVENT_TASK_ADMITTED = "EVENT_TASK_ADMITTED"
EVENT_STATUS_CHANGED = "EVENT_STATUS_CHANGED"
EVENT_LOCK_ACQUIRED = "EVENT_LOCK_ACQUIRED"
EVENT_LOCK_HELD = "EVENT_LOCK_HELD"
EVENT_LOCK_RELEASED = "EVENT_LOCK_RELEASED"
EVENT_RUN_STARTED = "EVENT_RUN_STARTED"
EVENT_RUN_FINISHED = "EVENT_RUN_FINISHED"
EVENT_GATES_EVALUATED = "EVENT_GATES_EVALUATED"
EVENT_RETRY_SCHEDULED = "EVENT_RETRY_SCHEDULED"
EVENT_DEAD_LETTERED = "EVENT_DEAD_LETTERED"

# Queue field names
FIELD_TASK_ID = "task_id"
FIELD_STATUS = "status"
FIELD_TASK_FILE = "task_file"
FIELD_RETRIES = "retries"
FIELD_MAX_RETRIES = "max_retries"
FIELD_RETRY_DELAY_SECONDS = "retry_delay_seconds"
FIELD_NEXT_ATTEMPT_AT = "next_attempt_at"
FIELD_FAILURE_REASON = "failure_reason"
FIELD_DEAD_LETTER_REASON = "dead_letter_reason"
FIELD_INVARIANT_VIOLATION = "invariant_violation"
FIELD_LAST_EXIT_CODE = "last_exit_code"
FIELD_HARNESS_LOG_PATH = "harness_log_path"


# Deterministic task lifecycle:
# QUEUED can fail preflight checks before entering EVALUATING, so QUEUED->FAILED
# is allowed and retry/backoff can apply safely.
# Terminal states remain terminal.
ALLOWED_TRANSITIONS = {
    QUEUED: {EVALUATING, FAILED},
    EVALUATING: {COMPLETED, REFUSED, FAILED},
    FAILED: {QUEUED, DEAD_LETTER},
    REFUSED: set(),
    COMPLETED: set(),
    DEAD_LETTER: set(),
}
